### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#107]
Should be able to do this while maintaining Python 2 compatibility for now. [requires.io](https://requires.io/github/WISVCH/dienst2/requirements/?branch=master) shows that all of our libs except for python-ldap are compatible. [django-python3-ldap now works with Python 2](https://github.com/etianen/django-python3-ldap/pull/24) but hasn't seen a release yet; we can include it from GitHub for now.

**Comment by jgadelange** [comment]
[![Can I Use Python 3?](https://caniusepython3.com/check/2d434a16-c64c-4d87-b524-9f55127d2db8.svg)](https://caniusepython3.com/check/2d434a16-c64c-4d87-b524-9f55127d2db8) Seems like it should work already...

**Comment by praseodym** [comment]
python-ldap doesn't have a Python 3 version, so not sure how that check works..

**Comment by praseodym** [comment]
How did you get that badge? If I use the `requirements.txt` URL we get this one:
[![Can I Use Python 3?](https://caniusepython3.com/check/1c14ec8d-218f-4c70-88f1-d3fe8eb91c82.svg)](https://caniusepython3.com/check/1c14ec8d-218f-4c70-88f1-d3fe8eb91c82)

**Comment by praseodym** [comment]
django-auth-ldap 1.2.7 [supports Python 3 with pyldap](https://bitbucket.org/psagers/django-auth-ldap/commits/d8499abfcd13d26d57977ba94c35d7e8b2fe4dee).

**Comment by praseodym** [comment]
https://docs.djangoproject.com/en/1.8/topics/migrations/#supporting-python-2-and-3 should fix current database errors (via https://code.djangoproject.com/ticket/24884)

**Comment by jgadelange** [comment]
Still broken (found so far):
[ ] ldb: export
[ ] post: autocomplete

**Comment by praseodym** [comment]
Looks like ldb export is also broken in `master` :')

**Comment by praseodym** [comment]
Export works again, anything else? :)

**Comment by praseodym** [comment]
🎉
