### ISSUE TITLE
accounts/login redirects to /

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#110]
`https://frans.chnet/dienst2/accounts/login/` redirects to `https://frans.chnet/` after login :unamused:

**Comment by svenvanhal** [comment]
Oei gelijk alweer kapot :speak_no_evil:

**Comment by svenvanhal** [comment]
Geen regressie door #108, maar een bug die per ongeluk nooit ontdekt is. Zit 'm in deze regel: https://github.com/WISVCH/dienst2/blob/master/dienst2/settings.py#L113.

Moeten rekening houden met een eventuele subdir waar dienst in draait.

**Comment by jgadelange** [comment]
Is nooit opgevallen omdat we nooit gelinkt hebben naar de login pagina.. Volgens mij is het ook bijna onmogelijk om dit aan te passen. Al zou het gewoon opgelost kunnen worden door de local.py op de server te overschrijven (lijkt me de beste oplossing)

**Comment by jgadelange** [comment]
Gefixt door de local.py aan te passen op frans.
