### ISSUE TITLE
Leden 'niet lid' bij aanmaken

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/dienst2#114]
Als er een nieuw persoon wordt toegevoegd dat lid is, staat er toch 'niet lid' achter de naam op de detailpagina. Als je de persoon dan opnieuw opent en opslaat, staat het wel goed. De controle of een nieuw persoon lid is gaat dus niet goed bij het aanmaken.

**Comment by praseodym** [comment]
Oplossing is waarschijnlijk een `person.save()` in [ldb/views.py](https://github.com/WISVCH/dienst2/blob/ed6e66059d6431c466693c29e6fe0222c96d168d/ldb/views.py#L175-L186).

Verder is het nuttig om te checken of de Django admin interfaces hetzelfde probleem heeft.

**Comment by jgadelange** [comment]
Hmmmm... Django admin does not seem to have the same problem.
