### ISSUE TITLE
Django 1.10 upgrade

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#118]
See [release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/) including [removed features](https://docs.djangoproject.com/en/1.9/releases/1.9/#removed-features-1-9). We should probably update all dependencies and maybe fix #107 first.

Packages not compatible with django 1.10:
 * [django-enumfield](https://github.com/5monkeys/django-enumfield/)

**Comment by praseodym** [comment]
Django 1.10 has been released as well: https://docs.djangoproject.com/en/dev/releases/1.10/

**Comment by jgadelange** [comment]
After de upgrade we should change the line in `.travis.yml` that checks for migrations to use the [new `--check` flag](https://docs.djangoproject.com/en/1.10/ref/django-admin/#cmdoption-makemigrations--check).

**Comment by jgadelange** [comment]
Added this to hoothub, don't think this is a beginner task though. And have no idea how long it will take.
The number of uilenballen will be determined after finishing the upgrade 😉

**Comment by jgadelange** [comment]
Ok, I made a start. I will keep a list of issues in the original text

**Comment by jgadelange** [comment]
In the `django-upgrade` branch django is updated to 1.9, and other dependencies to latest version. 

Before upgrading to django 1.10 we should first do something about `django-enumfield`
