### ISSUE TITLE
Replace Elasticsearch by PostgreSQL queries

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#136]
Django 1.10 (#118) [supports full text search for PostgreSQL](https://docs.djangoproject.com/en/dev/ref/contrib/postgres/search/). This might be a viable replacement for the current Haystack/Whoosh/Elasticsearch setup.

**Comment by jgadelange** [comment]
Full text search isnt good for partial search. E.g. searching for "jeff" doesnt find "jeffreyl".
But we can also change to `__icontains` queries.

I will add some code samples here for both Full Text Search and the `__icontains` soon!

**Comment by JoepdeJong** [comment]
I've made the switch to `__icontains`

**Comment by jgadelange** [comment]
As far as I can see you still use haystack. So the elastic search dependency is still there. To remove the dependency all references to haystack should be replaced (so just use the normal queryset and filter on that). 

I see I promised examples 🙈 I'm afraid I won't be able to create those in the short term, but feel free to ask questions if you need any further directions.

**Comment by JoepdeJong** [comment]
Do we still need the indices in `ldb/search_indexes` when switching to `__icontains`? Any suggestions for replacing those?

**Comment by jgadelange** [comment]
The search indices are only necessary when you use `haystack` as search engine. If we replace that with a normal query (`Person.objects.filter(..._icontains=<>)`) they shouldn't be necessary anymore.

**Comment by praseodym** [comment]
Should be completed by #313, #314, #319.
