### ISSUE TITLE
Dockerfile does not work out of the box on Docker for Windows (Toolbox)

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/dienst2#183]
`docker-compose up --build` output:

`ERROR: for django  Cannot start service django: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/srv/docker-entrypoint-dev.sh\": stat /srv/docker-entrypoint-dev.sh: no such file or directory"`

It's quite hard to debug which files are copied to where when the container cannot be started, but it seems that not all (and maybe none) of the project files are copied into the image on build. This might have to do with the volume directive in the docker-compose file, since the behavior of volumes differs from Windows to *nix.

Need to look into this further, leaving this for future reference.

**Comment by praseodym** [comment]
Maybe the sh file is just missing the executable bit when building on Windows?

**Comment by svenvanhal** [comment]
That didn't solve it (as the file is really not copied into the image).

This did solve it (but I don't know if it breaks something else):

Changing [this line](https://github.com/WISVCH/dienst2/blob/516c6e8fff6cceb4c93ae6dec38fe130213defba/Dockerfile-dev#L4) to `COPY . /srv/` in Dockerfile-dev and removing [this line](https://github.com/WISVCH/dienst2/blob/516c6e8fff6cceb4c93ae6dec38fe130213defba/docker-compose.yml#L12) in docker-compose.yml.

**Comment by praseodym** [comment]
That breaks the development flow: using a volume mount ensures that source files edited outside the container are immediately available inside the container. This allows one to edit source files and immediately see those changes, without having to rebuild the container at all.

If `docker-entrypoint-dev.sh` is the problem, we could copy only that file into the container
