### ISSUE TITLE
Deployment: remove memcached

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#294]
Let's just create sessions in the database instead of deploying memcached.

**Comment by jgadelange** [comment]
Isn't memcached use for caching instead of sessions? 🤔

**Comment by praseodym** [comment]
Production config is as follows:
```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': 'localhost:11211',
        'KEY_PREFIX': 'dienst2',
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
```
And I don't think the cache is used anywhere else?

**Comment by jgadelange** [comment]
Django does some automatic caching for some stuff, but not sure what exactly 😅 

We could also switch the [cache to db](https://docs.djangoproject.com/en/3.2/topics/cache/#database-caching) or maybe [local memory](https://docs.djangoproject.com/en/3.2/topics/cache/#local-memory-caching)

**Comment by praseodym** [comment]
Local memory cache + sessions in database sounds like the way to go.

**Comment by JoepdeJong** [comment]
Resolved with https://github.com/WISVCH/dienst2/pull/311
