### ISSUE TITLE
66 - Members in Dienst

### ISSUE THREAD

**Issue by larsvantol** [WISVCH/dienst2#305]
Currently, members register by buying a ticket in events and then filling out a Google Form. Then manually who from the google form bought a ticket is checked by the secri. Then another new excel is created where all the data is correct. Then when this is imported into Dienst often a lot of errors appear because a lot of information is not filled in correctly by the students. Finally, everyone has to be manually emailed that they have an account and how to log in.

Is it possible to have members automatically enrolled in Service? For example, by filling out a form on the website and then paying. Julian recently showed an advanced beta version, is it possible to implement it?

**Comment by JoepdeJong** [comment]
i close this issue, as this request is about another repository that is still work in progress.
