### ISSUE TITLE
66 - Edit Profile werkt niet

### ISSUE THREAD

**Issue by larsvantol** [WISVCH/dienst2#306]
Momenteel werkt de pagina edit profile niet (https://ch.tudelft.nl/portal/edit-profile/)

Bij het veranderen van profielgegevens zoals adres , telefoonnummer, naam etc. verschijnt er een error:

![image](https://user-images.githubusercontent.com/4377948/214512685-cfcc6d12-f93c-4eae-9abf-f27f7ef8ef02.png)

Verder zijn er onlangs meerdere genders toegevoegd in dienst, maar deze verschijnen ook niet op deze pagina.

Daarnaast zou het ook erg fijn zijn als studenten zelf kunnen zien voor welke mail lijsten ze zijn ingeschreven en dat ze hier zichzelf ook handmatig voor kunnen uitschrijven. Momenteel gaat dit allemaal handmatig via de secretaris en kost dit een hele hoop werk.

**Comment by JoepdeJong** [comment]
Het bewerken van gegevens vanuit de WordPress website is momenteel niet mogelijk omdat er geen publieke API beschikbaar is voor Dienst. @julian9499 is hier wel mee bezig geweest voor het member registration systeem. Als dat draait kan ik dat modificeren om het bewerken van gegevens vanuit de website te ondersteunen. Dat vereist wel wat aanpassingen aan Connect.

**Comment by praseodym** [comment]
Er is wel gewoon een API voor Dienst2 beschikbaar. Dit lijkt me een bug in de website, niet in Dienst2.
