### ISSUE TITLE
66 - Committee export

### ISSUE THREAD

**Issue by larsvantol** [WISVCH/dienst2#307]
Currently it is not possible to export committee members in service, for example for sending Christmas cards or creating a mailing list.

It is possible to get a list of committee members from a certain year (https://dienst2.ch.tudelft.nl/ldb/committees/?board=66&committee=).

But here you cannot download an overview of data, as, for example, you can here when exporting LvV'ers (https://dienst2.ch.tudelft.nl/ldb/export/#/).

**Comment by praseodym** [comment]
Related to #92
