### ISSUE TITLE
Reversion version

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#37]
[error] /srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/reversion/__init__.py:38: UserWarning: django-reversion 1.6.5 is intended for use with django 1.4.0 or 1.4.1 or 1.4.2 or 1.4.3. You are running django 1.4.8, so some features, such as admin integration, may not work. Please see https://github.com/etianen/django-reversion/wiki/Compatible-Django-Versions
    [error]   "django_version": format_version(django.VERSION[:3]),

**Comment by jgadelange** [comment]
Fixed door upgrade

**Comment by praseodym** [comment]
Volgens mij had ik 'm er zelfs al uit gehaald met een minor upgrade, maar hij kan idd dicht :)
