### ISSUE TITLE
Kas: form based views

### ISSUE THREAD

**Issue by jgadelange** [WISVCH/dienst2#57]
After #50 we should also convert the kas app to form based views

**Comment by svenvanhal** [comment]
Sneak peek?

![kas_sneakpeek](https://cloud.githubusercontent.com/assets/579633/11966683/896b4790-a8fd-11e5-95b7-57f70c76a1bc.PNG)

**Comment by praseodym** [comment]
https://github.com/WISVCH/dienst2/issues/213
