### ISSUE TITLE
Typeahead in post werkt niet meer

### ISSUE THREAD

**Issue by sanderploegsma** [WISVCH/dienst2#60]
Ik meen me te herinneren dat hij vroeger suggesties gaf, nu werkt het pas als je een woord volledig intypt (bijvoorbeeld 'Overig')

**Comment by praseodym** [comment]
Weet niet helemaal of dit het fixen waard is als we #58 hebben

**Comment by sanderploegsma** [comment]
Geen idee, maar een typeahead heeft op deze manier uberhaupt geen zin.

**Comment by praseodym** [comment]
Ik krijg helemaal geen typeahead trouwens..

**Comment by sanderploegsma** [comment]
Als het goed is moet het werken in alles behalve description

**Comment by jgadelange** [comment]
Is dit kapot gegaan door: 080979b338a3154b25f1f31297ba81d5503cac68?

**Comment by jgadelange** [comment]
Zoeken op personen werkt ook niet helemaal lekker meer

**Comment by praseodym** [comment]
Lijkt inderdaad alleen exact matches te doen..

**Comment by praseodym** [comment]
http://django-haystack.readthedocs.org/en/latest/autocomplete.html#step-1-setup-the-data
Oude oplossing was ranzig, (`Edge`)`NgramField` zou beter moeten zijn.

**Comment by jgadelange** [comment]
Fixed by 5e6d5bd95ef1d4cd28bb8e5a339ab15075616c82
