### ISSUE TITLE
info ballon bij aanmeldingen

### ISSUE THREAD

**Issue by karensg** [WISVCH/dienst2#8]
![capture](https://f.cloud.github.com/assets/359682/567841/4b5fb00e-c6c3-11e2-8c68-a2e694a54ad8.png)

Dus waar de uitnodigingen bestuur allemaal voor gebruikt worden.

**Comment by karensg** [comment]
6.5 jaar voorbij en ik ben nog steeds aan het wachten! @htdvisser, zeg er wat van

**Comment by htdvisser** [comment]
Ik vind het niet kunnen

**Comment by julian9499** [comment]
![image](https://user-images.githubusercontent.com/17440177/72110343-43fc1300-3338-11ea-86fb-977505c31ec5.png)
Tegenwoordig ziet het er zo uit. Toch een vooruitgang.

**Comment by julian9499** [comment]
Helaas support Django dat niet, maar we kunnen er wel een permanente hulptekst bij zetten!
![image](https://user-images.githubusercontent.com/17440177/72110898-a1dd2a80-3339-11ea-8244-422494d98cc8.png)

**Comment by JoepdeJong** [comment]
not needed anymore. fields will be removed in #326
