### ISSUE TITLE
Search result arrow key navigation

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#81]
- [ ] arrow key navigation
- [x] 'x more results' indicator
- [x] not show deleted objects in results?
- [x] Show number of results

**Comment by jgadelange** [comment]
https://github.com/WISVCH/dienst2/tree/fb-master_improve-search-results

**Comment by jgadelange** [comment]
<img width="520" alt="ledenadministratie_ _dienst2" src="https://cloud.githubusercontent.com/assets/432366/9056338/af261f5c-3a92-11e5-9015-fd3f12567df5.png">

**Comment by jgadelange** [comment]
Uilenballen for arrow key navigation!
