### ISSUE TITLE
Leden met gebruikersnaam bovenaan zoekresultaten

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/dienst2#90]
Wanneer je naar leden zoekt op naam, ben je vaak op zoek naar (actieve) leden met een CH gebruikersnaam. Daarom is het handig als juist die leden bovenaan de zoekresultaten staan, in plaats van tussen de andere leden (die misschien al lang niet meer studeren).

**Comment by praseodym** [comment]
Misschien aflopend sorteren op datum eerste lidmaatschap?

**Comment by jgadelange** [comment]
Kan je ElasticSearch niet beter allemaal fancy dingen met score laten doen ofzo?

**Comment by praseodym** [comment]
Dat kan vast wel, iets met lengte lidmaatschap, student ja/nee, CH username ja/nee, en aantal commissies?

**Comment by jgadelange** [comment]
Succes @svenvanhal! :stuck_out_tongue_winking_eye:

**Comment by praseodym** [comment]
http://django-haystack.readthedocs.org/en/latest/boost.html

**Comment by sanderploegsma** [comment]
CH-punten? :stuck_out_tongue_winking_eye:

**Comment by svenvanhal** [comment]
Ik heb nu de search template opgedeeld in drie stukken voor zowel personen als organisaties: ```name``` (naam, ldap_username, netid etc), ```address``` (adresgegevens) en ```contact``` (email en telnr etc.).

Elk van die drie heeft een ander zoekgewicht waardoor een name of ldap match nu bijvoorbeeld veel belangrijker is dan een match in de straatnaam.

Zou het probleem moeten oplossen, maar kan evt. nog uitgebreid worden met lengte- en soort lidmaatschap en/of aantal commissies.

**Comment by praseodym** [comment]
Goed bezig! Wat mij betreft kan LDAP username een apart index field worden zonder template, en met boost. Maar belangrijker is dat we moeten kijken wat voor boost values we moeten gebruiken:
> Be warned that boost is very, very sensitive & can hurt overall search quality if over-zealously applied. Even very small adjustments can affect relevance in a big way.

**Comment by jgadelange** [comment]
:+1: Lekker bezig! Ik denk alleen dat je nu nog niet bereikt hebt wat je in eerste instantie van plan was. Daarvoor moet je eigenlijk alleen de ldap username een boost geven, toch?

Ik denk dat je dus een alleen een `ldap_username = indexes.CharField(model_attr='ldap_username')` wilt toevoegen met een boost en verder gewoon de text wilt laten. (Zeker met die quote van mark erbij meegenomen). 

Daarnaast kan ik mij van de voorbeelden die ik heb bekeken boost waarden van 1.01 herinneren...

**Comment by svenvanhal** [comment]
Het boosten van de LDAP username is een beetje een quick fix, want eigenlijk wil je, zeker als je halve zoekwoorden gebruikt, gewoon meer waarde hechten aan de naam van een lid/organisatie dan aan een adres. Verder kan ik me wel vinden in het los boosten van de ldap_username hoor.

Boost waarden zijn nu inderdaad best ingrijpend, maar in de voorbeelden op de [Haystack site](http://django-haystack.readthedocs.org/en/latest/boost.html#field-boost) worden bijvoorbeeld ook waarden van 0.8 of 1.1 gebruikt.

**Comment by praseodym** [comment]
Boost van 1.1 is daar "slight increase" en 0.8 ineens is "big decrease", dus 1.5 en 0.5 lijkt me wat overdreven. Maar dat zal vooral een kwestie van testen zijn.

Meenemen van lidmaatschaptype kan een document boost worden; als we 'lid af' omlaag gooien dan komen we al een heel eind.

Verder lijk je met [`content`](http://django-haystack.readthedocs.org/en/latest/searchqueryset_api.html#the-content-shortcut) te kunnen voorkomen dat je elk field los moet meenemen in je query (in `ResultsView`).
